version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gov
      POSTGRES_PASSWORD: gov
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data



  es01:
    container_name: elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data


volumes:
  my-db:
  data: {}
  elasticsearch-data-volume:
    driver: local


networks:
  default:
    name: mongodb_network
